apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jumpstart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jumpstart
  minReplicas: {{ .Values.apps.jumpstart.hpa.min }}
  maxReplicas: {{ .Values.apps.jumpstart.hpa.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: {{ .Values.apps.jumpstart.hpa.threshold.cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.apps.jumpstart.hpa.threshold.ram }}
