apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpstart
spec:
  selector:
    matchLabels:
      app: jumpstart
  template:
    metadata:
      labels:
        app: jumpstart
    spec:
      containers:
        - name: jumpstart
          image: "digitranslab/jumpstart-ce:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: {{ .Values.apps.jumpstart.deployment.resources.limits.memory }}
              cpu: {{ .Values.apps.jumpstart.deployment.resources.limits.cpu }}
            requests:
              memory: {{ .Values.apps.jumpstart.deployment.resources.requests.memory }}
              cpu: {{ .Values.apps.jumpstart.deployment.resources.requests.cpu }}
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: JUMPSTART_HOST
              value: "{{ .Values.apps.jumpstart.service.host }}"
            - name: PG_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.apps.jumpstart.secret.name }}"
                  key: pg_user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.apps.jumpstart.secret.name }}"
                  key: pg_password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.apps.jumpstart.secret.name }}"
                  key: pg_db
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.apps.jumpstart.secret.name }}"
                  key: lockbox_key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.apps.jumpstart.secret.name }}"
                  key: secret_key_base
            - name: DEPLOYMENT_PLATFORM
              value: "k8s:helm"
