apiVersion: v1
kind: Service
metadata:
  name: jumpstart
spec:
  type: {{ .Values.apps.jumpstart.service.type }}
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: jumpstart
