previewsEnabled: false
previewsExpireAfterDays: 2
services:
  - type: web
    name: JumpStart
    env: docker
    repo: https://github.com/digitranslab/jumpstart.git
    dockerfilePath: ./docker/preview.Dockerfile
    dockerContext: ./
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-preview
          property: connectionString
      - key: JUMPSTART_DB
        value: 'jumpstart_db'
      - key: ENABLE_JUMPSTART_DB
        value: 'true'
      - key: JUMPSTART_HOST
        fromService:
          type: web
          name: JumpStart
          envVarKey: RENDER_EXTERNAL_URL
      - key: PGRST_HOST
        fromService:
          type: web
          name: PostgREST
          envVarKey: RENDER_EXTERNAL_URL
      - key: PORT
        value: 80
      - fromGroup: jumpstart-preview-env
  - type: web
    name: PostgREST
    env: docker
    repo: https://github.com/digitranslab/jumpstart.git
    dockerfilePath: ./docker/postgrest.render.Dockerfile
    dockerContext: ./
    envVars:
      - key: PGRST_ADMIN_SERVER_PORT
        value: 3001
      - key: PGRST_DB_URI
        fromDatabase:
          name: postgres-preview
          property: connectionString
      - key: PGRST_LOG_LEVEL
        value: 'info'
databases:
  - name: postgres-preview
    plan: starter
    databaseName: jumpstart_preview
    postgresMajorVersion: 13
