version: "3"

services:
  jumpstart:
    tty: true
    stdin_open: true
    container_name: jumpstart-app
    image: digitranslab/jumpstart-ce:latest
    restart: always
    env_file: .env
    ports:
      - 80:80
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod
  # Uncomment if ENABLE_JUMPSTART_DB=true
  postgrest:
    image: postgrest/postgrest:v12.0.2
    restart: always
    env_file: .env
    environment:
      - PGRST_SERVER_PORT=80
