apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpstart-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpstart-ce
  template:
    metadata:
      labels:
        app: jumpstart-ce
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: jumpstart-ce
        image: digitranslab/jumpstart-ce:latest
        imagePullPolicy: Always
        args: ["npm", "run", "start:prod"]
        resources:
          limits:
            memory: "2000Mi"
            cpu: "2000m"
          requests:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            port: 3000
            path: /api/health
          successThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 6
        env:
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: jumpstart-secret
                key: pg_host
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: jumpstart-secret
                key: pg_user
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: jumpstart-secret
                key: pg_pass
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: jumpstart-secret
                key: pg_db
          - name: LOCKBOX_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: jumpstart-secret
                key: lockbox_master_key
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: jumpstart-secret
                key: secret_key_base
          - name: JUMPSTART_HOST
            value: "https://jumpstart.your-domain.com"
          - name: DEPLOYMENT_PLATFORM
            value: "k8s:aks"
          # Set the env values below for Jumpstart Database
          # - name: ENABLE_JUMPSTART_DB
          #   value: "true"
          # - name: JUMPSTART_DB
          #   value: "jumpstart_db"
          # - name: JUMPSTART_DB_USER
          #   value: "replace_with_jumpstart_db_user"
          # - name: JUMPSTART_DB_HOST
          #   value: "replace_with_jumpstart_db_host"
          # - name: JUMPSTART_DB_PASS
          #   value: "replace_with_jumpstart_db_pass"
          # - name: PGRST_HOST
          #   value: "replace_with_postgrest_host"
          # - name: PGRST_JWT_SECRET
          #   value: "replace_pgrst_jwt_secret_here"
