apiVersion: v1
kind: Service
metadata:
  name: jumpstart-server
spec:
  type: LoadBalancer
  selector:
    component: jumpstart
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
